---
abstract: 'The great new Acme::Mandolion::Utils!'
author:
  - 'Julio de Leon <jangelod@gmail.com>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.141520'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Acme-Mandolion-Utils
provides:
  Acme::Mandolion::Utils:
    file: lib/Acme/Mandolion/Utils.pm
    version: '0.01'
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
version: '0.01'
